name: Build the paper
on:
    push: {}
    workflow_dispatch: {}

jobs:
    build-paper:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
          with:
        - uses: blytkerchan/build-paper@main
          with:
            filename: guidelines.ipynb
